### ISSUE TITLE
`ipfs pin ls` returns nothing after upgrade

### ISSUE THREAD

**Issue by leerspace** [ipfs/badgerds-upgrade#2]
After upgrading my badger datastore, `ipfs pin ls` now returns nothing.

This is with go-ipfs v0.4.12-rc2 on both linux and windows.

**Comment by magik6k** [comment]
Did you use the tool after the 'fix some issues' PC?

**Comment by leerspace** [comment]
I thought I did, but I'll try again.

**Comment by leerspace** [comment]
I started to re-process my 240 GB repository which would take until tomorrow, but then I realized that's unnecessary. I tried again with a fresh repo and reproduced the issue.

Here are the steps I did to reproduce:
1. `ipfs init --profile=badgerds` with v0.4.12-rc1
2. There are already several things pinned, but I also went ahead and did an `ipfs pin add -r Qmb8wsGZNXt5VXZh1pEmYynjB6Euqpq3HYyeAdw2vScTkQ` and verified it shows up in `ipfs pin ls --type=recursive`
3. Run `badgerds-upgrade upgrade` (after following the installation instructions)
4. Install v0.4.12-rc2
5. `ipfs pin ls` now returns nothing

**Comment by magik6k** [comment]
rc1 has yet another badger version shouldn't open as it has a different magic number (and it's not in ds-upgrade) . I'll look at it soon.

**Comment by leerspace** [comment]
For reference, the only reason I was using v0.4.12-rc1 is because v0.4.11 [doesn't run on Windows when using badger](https://github.com/ipfs/go-ipfs/issues/4242).

**Comment by magik6k** [comment]
Yeah, so it somehow worked in my tests earlier, now I'm getting multiple keys with different data from iterator, this probably has to do with having 2 versions of badger in one program. I guess I'll mark the thing as broken for now and look for a way to make it work again, though I may not be able to do it in a single binary..

**Comment by Kubuxu** [comment]
@magik6k you may need to vendor in the badger.

Does it currently lead to dataloss?

**Comment by leerspace** [comment]
At the very least the data about which hashes in the repo are pinned seems to be lost, but I don't know if the data exists in the repository in a usable form.

**Comment by magik6k** [comment]
This currently may cause dataloss/serious corruption, vendoring won't change much as it mostly caused by global state being shared between versions (That's the point of patching badger versions here, though I've most likely missed something). Using unpatched badger will be safer, though will result with multiple binaries and more complexity.. assuming it's not possible to vendor recursively.

**Comment by leerspace** [comment]
I deleted the backup on my linux laptop immediately after running the conversion (that's what I get for assuming without verifying), but I can confirm that there is a lot of corrupted data in the badgerds-upgrade upgraded datastore according to `ipfs repo verify`.

**Comment by Kubuxu** [comment]
@magik6k if the tool doesn't work, this needs to be escalated and fixed immediately.

**Comment by magik6k** [comment]
This should be fixed with https://github.com/ipfs/badgerds-upgrade/commit/87a2b6c3f602c5de9bd253ed887ba05ab4043115, do you mind re-checking?

**Comment by leerspace** [comment]
@magik6k That did the trick. Using the steps to reproduce earlier on in this thread I'm no longer seeing any missing pins and `ipfs repo verify` is not returning any corrupt blocks.
